name: .NET Core Dos

on:
  push:
    branches: [ "main", "master", "test" ]
  pull_request:
    branches: [ "main", "master", "test"  ]

jobs:
  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        #fetch-depth: 1 # hämta bara senaste
        fetch-depth: 0 # hämta information om alla commits
        
    # Install the .NET Core workload
    - name: Install .NET Core,
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Git log
      run : git log
