name: .NET Core Dos

on:
  push:
    branches: [ "main", "master", "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch information about all commits

    # Set the Git user identity to the GitHub Actions bot
    - name: Set Git user identity
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Check if push is triggered by script
      run: |
        if [[ "${{ github.actor }}" == "github-actions[bot]" ]]; then
          echo "Push is triggered by the script. Skipping..."
          exit 0
        fi

    - name: Generate human-readable Git log
      run: |
        git log --pretty=format:"[%s] (%h) %an - %s" > History.md

    # Generate the HTML code coverage report using ReportGenerator and save it
    - name: Generate and save coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage.opencover.xml -targetdir:coverage-report
      working-directory: ${{ github.workspace }}/path/to/coverage-folder
